#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

foreach $event (qw(
      nethserver-vpn-save
      nethserver-openvpn-save
      R2W-OTP-enable
    )) {
    event_actions($event, qw(
              nethserver-vpn-ui-find-forced-users-to-otp 10
    ));
}
