#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use File::Temp qw/tempfile/;
use MIME::Base64;

require '/usr/libexec/nethserver/api/nethserver-vpn-ui/lib/vpn_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

my $db = esmith::ConfigDB->open('vpn');
if ($cmd eq 'create-client') {

    $db->new_record($input->{'name'}, {'type' => 'tunnel', 'status' => 'enabled'});

    foreach (qw(LocalPeer Topology Digest Compression Cipher Mode RemotePort AuthMode RemotePeer Protocol Password User)) {
        $db->set_prop($input->{'name'}, $_, $input->{$_}) if (exists($input->{$_}))
    }

    foreach (qw(RemoteHost RemoteNetworks WanPriorities)) {
        $db->set_prop($input->{'name'}, $_, join(',',@{$input->{$_}})) if (exists($input->{$_}));
    }

    if ($input->{'Psk'}) {
        write_file("/var/lib/nethserver/certs/clients/".$input->{'name'}.".key", $input->{'Psk'});
    }

    if ($input->{'Crt'}) {
        write_file("/var/lib/nethserver/certs/clients/".$input->{'name'}.".pem", $input->{'Crt'});
    }

} elsif ($cmd eq 'create-server') {

    $db->new_record($input->{'name'}, {'type' => 'openvpn-tunnel-server', 'status' => 'enabled'});

    foreach (qw(PublicAddresses RemoteNetworks LocalNetworks)) {
        $db->set_prop($input->{'name'}, $_, join(',',@{$input->{$_}})) if (exists($input->{$_}));
    }

    foreach (qw(Topology Digest Compression Cipher TlsVersionMin Protocol Port Network LocalPeer RemotePeer)) {
        $db->set_prop($input->{'name'}, $_, $input->{$_}) if (exists($input->{$_}));
    }

    if ($input->{'Psk'}) {
        write_file("/var/lib/nethserver/openvpn-tunnels/".$input->{'name'}.".key", $input->{'Psk'});
    }

} elsif ($cmd eq 'upload') {

   my $data = decode_base64($input->{'data'});
   my ($fh, $filename) = tempfile();
   write_file($filename, $data);
   system(("/sbin/e-smith/signal-event", "-j", "openvpn-tunnel-upload", $filename));
   exit $?;
    
} else {
    error();
}

system(("/sbin/e-smith/signal-event", "-j", "openvpn-tunnel-create", $input->{'name'}));
