#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use esmith::NetworksDB;
use NetAddr::IP;
use JSON;

require '/usr/libexec/nethserver/api/nethserver-vpn/lib/vpn_functions.pl';

my $action = shift || exit 0;
my $value = shift || exit 0;
my $current = shift || undef;

# actions is case insensitive
$action = lc($action);

# exit non-zero if the port or network is in use
if ($action eq 'port') {
    exit is_used_port($value, $current);
} elsif ($action eq 'network') {
    exit is_used_network($value, $current);
}
