#!/usr/bin/perl

# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro();
my $vdb = esmith::ConfigDB->open_ro('vpn');
my $AuthMode = $db->get_prop('openvpn@host-to-net','AuthMode') || 'password';
my $status = $db->get_prop('openvpn@host-to-net','status') || 'disabled';

# first remove 
unlink (glob("/var/lib/nethserver/openvpn-certificate-otp/*"));

if (($status  eq 'enabled') && ( $AuthMode eq 'certificate-otp')) {
    # we add the file openvpn-certificate-otp/user@domain.org if :
    #   AuthMode is certificate-otp 
    #   R2W is enabled
    #   client type is vpn-user
    #   client is enabled
    # If we find this file, we display a checkbox (disabled, checked) in the user setting page
    
    foreach ($vdb->get_all_by_prop('type', 'vpn-user')) {
        my $key = $_->key;
        my $userEnabled = $vdb->get_prop($key,'status') || 'enabled';
        next if ($userEnabled ne 'enabled');
        open my $f, '>', "/var/lib/nethserver/openvpn-certificate-otp/$key";
        close $f;
    }
}
