#!/usr/bin/env python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sqlite3
import simplejson

conn = sqlite3.connect('/var/lib/nethserver/openvpn/connections.db')
c = conn.cursor()

accounts = []
rows = c.execute('''SELECT common_name, MAX(start_time) 
					FROM connections
					GROUP BY common_name''')

for row in rows:
	accounts.append({'account': row[0], 'lastConnected': row[1]})

conn.close()
print(simplejson.dumps(accounts))
