#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/nethserver-vpn-ui/lib/vpn_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

if ($cmd eq 'create-account') {
    my $vdb = esmith::ConfigDB->open('vpn');
    $vdb->new_record($input->{'name'}, {type => $input->{'type'}, status => 'enabled'});

    foreach (qw(OpenVpnIp VPNRemoteNetmask VPNRemoteNetwork)) {
        $vdb->set_prop($input->{'name'}, $_, $input->{$_});
    }
    system(("/usr/libexec/nethserver/pki-vpn-gencert", $input->{'name'}));

    if ($input->{'OpenVpnIp'} ne '') {
        $input->{'name'} =~ s/(@.*)$//; # remove domain part
        openvpn_create_host($input->{'name'}, $input->{'OpenVpnIp'});
    }

    #we add the file openvpn-certificate-otp/user@domain.org if AuthMode is certificate-otp 
    # and client type is vpn-user
    my $db = esmith::ConfigDB->open_ro();
    my $AuthMode = $db->get_prop('openvpn@host-to-net','AuthMode') || 'password';
    if (($input->{'type'} eq 'vpn-user') && ($AuthMode eq 'certificate-otp')) {
        open my $FILE, ">>", "/var/lib/nethserver/openvpn-certificate-otp/$input->{'name'}" || die("Cannot open file:".$!);
        print $FILE "";
        close($FILE);
    }

} else {
    error();
}
system(("/sbin/e-smith/signal-event", "-j", "nethserver-openvpn-save"));
