#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/nethserver-vpn/lib/vpn_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

if ($cmd eq 'update-account') {
    my $vdb = esmith::ConfigDB->open('vpn');

    foreach (qw(OpenVpnIp VPNRemoteNetmask VPNRemoteNetwork)) {
        $vdb->set_prop($input->{'name'}, $_, $input->{$_});
    }
    if ($input->{'OpenVpnIp'} ne '') {
        $input->{'name'} =~ s/(@.*)$//; # remove domain part
        openvpn_create_host($input->{'name'}, $input->{'OpenVpnIp'});
    }

} elsif ($cmd eq 'configuration') {

    my $db = esmith::ConfigDB->open();
    foreach (keys %$input) {
        next if ($_ eq 'action');
        if ($_ eq 'Remote') {
            $db->set_prop('openvpn@host-to-net', $_, join(",",@{$input->{$_}}));
        } else {
            $db->set_prop('openvpn@host-to-net', $_, $input->{$_});
        }
    }

} else {
    error();
}
system(("/sbin/e-smith/signal-event", "-j", "nethserver-openvpn-save"));

